# .github/workflows/pull-request-close.yaml
name: Pull Request Closed

on:
  pull_request:
    types: [closed]

jobs:
  clean-up:
    name: Clean Up Preview UI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-2

      - name: Remove from S3
        run: |
          export REPO_NAME=$(jq -r '.pull_request.base.repo.name' $GITHUB_EVENT_PATH)
          export BUILD_ID=$(jq '.number' $GITHUB_EVENT_PATH)
          ./scripts/aws/remove-preview-bucket.sh "$REPO_NAME-pr-$BUILD_ID"
